#pragma once
#include <pebble.h>
#define SETTINGS_KEY 1
// A structure containing our settings
typedef struct ClaySettings {
  GColor FrameColor;
//  GColor FrameColor1;
  GColor FrameColor2;
  GColor SideColor1;
  GColor SideColor2;
  GColor Text1Color;
  GColor Text2Color;
  GColor Text3Color;
  GColor Text4Color;
  GColor Text5Color;
  GColor Text6Color;
  GColor Text7Color;
  GColor Text8Color;
  GColor Text9Color;
  GColor Text10Color;
  /////////////////
  GColor HourColor;
  GColor MinColor;
  GColor DateColor;
  GColor HourColorN;
  GColor MinColorN;
  GColor DateColorN;
  ////////////////
  GColor FrameColorN;
//  GColor FrameColor1N;
  GColor FrameColor2N;
  GColor SideColor1N;
  GColor SideColor2N;
  GColor Text1ColorN;
  GColor Text2ColorN;
  GColor Text3ColorN;
  GColor Text4ColorN;
  GColor Text5ColorN;
  GColor Text6ColorN;
  GColor Text7ColorN;
  GColor Text8ColorN;
  GColor Text9ColorN;
  GColor Text10ColorN;
  int WeatherUnit;
  char* WindUnit;
  int UpSlider;
  char* WeatherTemp;
  char* TempFore;
//  char FontChoice[12];
  char moonstring[4];
  char sunsetstring[6];
  char sunrisestring[6];
  char sunsetstring12[6];
  char sunrisestring12[6];
  char tempstring[8];
  char condstring[4];
  char windstring[10];
  char windavestring[10];
  char iconnowstring[4];
  //char* iconnowstring;
  char iconforestring[4];
  char icon1hstring[4];
  char windiconnowstring[4];
  char windiconavestring[4];
  char templowstring[6];
  char temphistring[10];
  char rainstring[10];
  char popstring[6];
  int Weathertimecapture;
  bool NightTheme;
  bool HealthOff;
  bool VibeOn;
  bool AddZero12h;
  bool RemoveZero24h;
  char raintime24h[6];
  char raintime12h[6];
  char* RainUnit;
  #ifdef PBL_MICROPHONE
  bool UsePWS;
  char windstringpws[10];
  char tempstringpws[6];
  char windiconnowstringpws[4];
  char pressurestringpws[6];
  char precipratestringpws[6];
  char preciptotalstringpws[6];
  char* PressureUnit;
  #endif
  int rain5;
  int rain15;
  int rain25;
  int rain35;
  int rain45;
  int rain55;
  int Rainmultiplier;
  int rain0;
  int rain10;
  int rain20;
  int rain30;
  int rain40;
  int rain50;
  int rain60;
} __attribute__((__packed__)) ClaySettings;
