#pragma once
#include <pebble.h>
#define SETTINGS_KEY 1
// A structure containing our settings
typedef struct ClaySettings {
  GColor FrameColor;
//  GColor FrameColor1;
  GColor FrameColor2;
  GColor SideColor1;
  GColor SideColor2;
  GColor Text1Color;
  GColor Text2Color;
  GColor Text3Color;
  GColor Text4Color;
  GColor Text5Color;
  GColor Text6Color;
  GColor Text7Color;
  GColor Text8Color;
  GColor Text9Color;
  GColor Text10Color;
  /////////////////
  GColor HourColor;
  GColor MinColor;
  GColor DateColor;
  GColor HourColorN;
  GColor MinColorN;
  GColor DateColorN;
  ////////////////
  GColor FrameColorN;
//  GColor FrameColor1N;
  GColor FrameColor2N;
  GColor SideColor1N;
  GColor SideColor2N;
  GColor Text1ColorN;
  GColor Text2ColorN;
  GColor Text3ColorN;
  GColor Text4ColorN;
  GColor Text5ColorN;
  GColor Text6ColorN;
  GColor Text7ColorN;
  GColor Text8ColorN;
  GColor Text9ColorN;
  GColor Text10ColorN;
  GColor UVMaxColor;
  GColor UVNowColor;
  GColor UVArcColor;
  GColor UVValColor;
  GColor UVMaxColorN;
  GColor UVNowColorN;
  GColor UVArcColorN;
  GColor UVValColorN;
  int WeatherUnit;
  char WindUnit [8];
  int UpSlider;
  char WeatherTemp [8];
  char TempFore [10];
//  char FontChoice[12];
  char moonstring[4];
  char sunsetstring[8];
  char sunrisestring[8];
  char sunsetstring12[8];
  char sunrisestring12[8];
  char tempstring[8];
  char condstring[4];
  char windstring[10];
  char windavestring[10];
  char iconnowstring[4];
  //char* iconnowstring;
  char iconforestring[4];
  char icon1hstring[4];
  char windiconnowstring[4];
  char windiconavestring[4];
  char templowstring[10];
  char temphistring[10];
  char rainstring[10];
  char popstring[10];
  int Weathertimecapture;
  bool NightTheme;
  bool HealthOff;
  bool VibeOn;
  bool AddZero12h;
  bool RemoveZero24h;
  char raintime24h[6];
  char raintime12h[6];
  char RainUnit [8];
  bool UseWeather;
  bool UseUVI;
  bool UseRainGraph;
  int UVIndexMax;
  int UVIndexNow;
  int UVIndexDay;
  // #ifdef PBL_MICROPHONE
  // bool UsePWS;
  // char windstringpws[10];
  // char tempstringpws[10];
  // char windiconnowstringpws[4];
  // char pressurestringpws[16];
  // char precipratestringpws[10];
  // char preciptotalstringpws[10];
  // char PressureUnit[10];
  // #endif
  int rain5;
  int rain15;
  int rain25;
  int rain35;
  int rain45;
  int rain55;
  int Rainmultiplier;
  int rain0;
  int rain10;
  int rain20;
  int rain30;
  int rain40;
  int rain50;
  int rain60;
} __attribute__((__packed__)) ClaySettings;
